version: "2"
services:
  app:
    build: ./
    links:
      - db
    #ports:
    #  - "5000:5000"
    tty: true

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: datascraper
      MYSQL_USER: root
    # Runs init.sql files to setup test data.
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
